### ISSUE TITLE
建议补充脚本执行说明

### ISSUE THREAD

**Issue by ym2011** [kafroc/-#1]
1、建议补充说明，如需要把busybox和chkrootkit同时上传到服务器
2、建议添加版本日期信息
3、错误修正
64行：s -alt /root/.ssh > /tmp/GatherInfo/ls_alt_root_.ssh.log 2>&1
应该是ls s -alt /root/.ssh > /tmp/GatherInfo/ls_alt_root_.ssh.log 2>&1

**Comment by kafroc** [comment]
已修正
